Ecommerce site/ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
    path('addtocart/<p>',views.add_to_cart,name="addtocart"),
    path('cartview',views.cartview,name="cartview"),
    path('cart_remove/<p>',views.cart_remove,name="cart_remove"),
    path('full_remove/<p>',views.full_remove,name="full_remove"),
    path('orderform', views.orderform, name="orderform"),
    path('orderview', views.orderview, name="orderview"),
]

Ecommerce site/ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart',include('cart.urls')),
    path('search',include('search.urls')),
]

if (settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Ecommerce site/ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [
    path('search',views.search,name="search"),
]

Ecommerce site/ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"
urlpatterns = [
    path('',views.allcategories,name="allcat"),
    path('allproducts/<p>',views.allproducts,name="allproducts"),
    path('detail/<p>',views.detail,name="detail"),
    path('reg',views.register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout"),

]

Ecommerce site/ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name
    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    product= models.ForeignKey(Product, on_delete=models.CASCADE)
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    no_of_items = models.IntegerField()
    address=models.TextField()
    phone=models.CharField(max_length=30)
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=30,default="pending")
    date_ordered=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username

class Account(models.Model):
    acctnum=models.CharField(max_length=20)
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnum

Ecommerce site/ecommerce/search/models.py
from django.db import models

# Create your models here.

Ecommerce site/ecommerce/shop/models.py
from django.db import models

class Category(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    image=models.ImageField(upload_to='shop/categories',blank=True,null=True)
    def __str__(self):
        return self.name


class Product(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    image=models.ImageField(upload_to='shop/categories',blank=True,null=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

Ecommerce site/ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from shop.models import Product
from cart.models import Cart
from cart.models import Account,Order
def cartview(request):
    total=0
    u=request.user
    try:
        cart=Cart.objects.filter(user=u)
        for i in cart:
            total+=i.quantity*i.product.price

    except:
        pass

    return render(request,'cart.html',{'c':cart,'total':total})



@login_required
def add_to_cart(request,p):
    product=Product.objects.get(name=p)#retrieved clicked product details from database
    u=request.user   #retrived the name of current login user
    try:
        cart=Cart.objects.get(user=u,product=product)#Checking the product is already in the cart
        if(cart.quantity<cart.product.stock): # condition:if quantity is less than stock give+1
             cart.quantity+=1 #if present incriment the quantity
        cart.save()
    except: #if not add a new record to the cart
        cart = Cart.objects.create(product=product, user=u, quantity=1)
        cart.save()  # both datas added to cart table



    return redirect('cart:cartview')
def cart_remove(request,p):
    p=Product.objects.get(name=p)
    user=request.user
    try:
        cart=Cart.objects.get(user=user,product=p)
        if cart.quantity>1:
            cart.quantity-=1

            cart.save()
        else:
            cart.delete()
    except:
        pass
    return redirect('cart:cartview')


def full_remove(request, p):
    p = Product.objects.get(name=p)
    user = request.user
    try:
        cart = Cart.objects.get(user=user, product=p)

        cart.delete()
    except:
        pass
    return redirect('cart:cartview')


def orderform(request):
    if (request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']
        u=request.user
        cart=Cart.objects.filter(user=u)


        #total amount
        total=0
        for i in cart:
            total+=i.quantity*i.product.price

        #check whether user has sufficient amount in account-
        ac=Account.objects.get(acctnum=n)
        if(ac.amount>=total):
            ac.amount=ac.amount-total
            ac.save()

            for i in cart:#creates record in order table for each object in cart table for the current user
                o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                o.save()
                i.product.stock=i.product.stock-i.quantity
                i.product.save()
            cart.delete()#clear the cart items for current user
            msg="Order Placed Successfully"
            return render(request,'orderdetail.html',{'m':msg})
        else:
            msg="Insufficient Amount in user Account.You cannot place order."
    return render(request,'orderform.html')
def orderview(request):
    u= request.user
    o=  Order.objects.filter(user=u)
    return render(request,'orderview.html',{'u':u.username,'o':o})

Ecommerce site/ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
def search(request):
    q=""
    product=None
    if(request.method=="POST"):
        q=request.POST['q']
        if q:
            product=Product.objects.filter(Q(name__icontains=q)|Q(desc__icontains=q))
    return render(request,'search.html',{'p':product,'query':q})

Ecommerce site/ecommerce/shop/views.py
from django.shortcuts import render,redirect
from shop.models import Category,Product
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

def allcategories(request):
    c=Category.objects.all()
    return render(request,'category.html', {'c':c})
def allproducts(request,p):
    c=Category.objects.get(name=p)
    p=Product.objects.filter(category=c)
    return render(request,'product.html',{'c':c,'p':p})
def detail(request,p):
     product=Product.objects.get(name=p)
     return render(request,'detail.html',{'p':product})
def register(request):
    if request.method == "POST":
        u = request.POST['u']
        p = request.POST['p']
        cp =request.POST['cp']
        e  =request.POST['e']


        if(p==cp):
            u=User.objects.create_user(username=u,password=p,email=e)
            u.save()
            return redirect('shop:allcat')
        else:
            return HttpResponse("Password Not Matching")

    return render(request,'register.html')
def user_login(request):
    if request.method=="POST":
        name=request.POST['u']
        pass1=request.POST['p']
        user=authenticate(username=name,password=pass1)
        if user:
            login(request,user)
            return redirect('shop:allcat')
        else:
            messages.error(request,"Invalid Credentials")
    return render(request,'login.html')

@login_required
def user_logout(request):
    logout(request)
    return user_login(request)

Ecommerce site/ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
<header>
    <center><img src="{% static 'images/img.png' %}" class= "mb-2" height="100px" width="100px"></center>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"> My Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:allcat' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.name %}">{{i.name}}</a></li>{% endfor %}

          </ul>
        </li>
          {% if user.is_authenticated %}
          {% if user.is_superuser == False %}
          <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping" style="font-size:25px;"></i>&nbsp;&nbsp;&nbsp;{{count}}</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'cart:orderview' %}">Your Orders</a>
          </li>
          {% endif %}
          <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
          </li>
          {% else %}

          <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'shop:register' %}">Register</a>
          </li>
        <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'shop:login' %}">Login</a>
          </li>
       {% endif %}

      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {%csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-dark" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</header>
{% block content %}
{% endblock %}
<footer>
<div class=" mt-5 footer">
    <p><i class="fa-regular fa-copyright"></i>Myshop pvt ltd.All Rights Reserved.</p>
</div>
</footer>

</body>
</html>

Ecommerce site/ecommerce/templates/cart.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if not c %}
<div class="container-fluid mt-3">
    <h3 class="text-center">Cart is empty</h3>
    <h5 class="text-center text-success"><a href="{% url 'shop:allcat' %}">Continue Shopping</a></h5>
</div>

{% else %}
<div class="container-fluid m-3">
<div class="row">
    <h4 class="text-center">SHOPPING CART</h4>


    <div class="col-sm-6">
        <table class="table table-bordered">
            <tr><th colspan="5" class="text-center">CART ITEMS</th></tr>
            {% for i in c %}
        <tr><td><img src="{{i.product.image.url}}" height="150px" width="150px"</td>
            <td><b>{{i.product.name}}</b></td>
            <td><b>Product id:{{i.product.id}}</b><br>
            <b>UnitPrice:{{i.product.price}}</b><br>
            <b>Quantity:{{i.quantity}}*{{i.product.price}}</b></td>

            <td>Subtotal:{{i.subtotal}}</td>
            <td>
                {% if i.quantity < i.product.stock %}
               <b><a href="{% url 'cart:addtocart' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-solid fa-circle-plus"></i></a>
            <a href="{% url 'cart:cart_remove' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-solid fa-circle-minus"></i></a>
            <a href="{% url 'cart:full_remove' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-solid fa-trash-can"></i></a></td></b>
{% else %}
             <b></b><a href="{% url 'cart:cart_remove' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-solid fa-circle-minus"></i></a>
            <a href="{% url 'cart:full_remove' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-solid fa-trash-can"></i></a></td></b>
        </tr>
        {% endif %}
 {% endfor %}
        </table>
    </div>

    <div class="col-sm-4" style="position:relative">
        <table class="table table-bordered">
        <tr><th colspan="4" class="text-center">CHECK OUT</th></tr>
            <tr><td class="text-center"><b>TOTAL: <span class="text-danger">{{total}}</span></b></td></tr>
        </table>
        <a href="{% url 'cart:orderform' %}" class="btn btn-primary text-dark"><b>Place Order</b></a>
        <a href="{% url 'shop:allcat' %}" class="btn btn-primary text-dark" style="position:absolute;right:0;"><b>Continue Shopping</b></a>
    </div>

</div>
</div>
{% endif %}
  {% endblock %}

Ecommerce site/ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'images/banner.png' %}" height="400px" width="100%">
</div>
<div class="container-fluid mt-5" style="margin-bottom:50px;">
    <h3 class="text-center fw-bold">Our Collections</h3>
    <p style="line-height:1.8;text-align:justify;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>

</div>
<div class="container=fluid mt-2 rounded rounded-5" style="margin-bottom:100px;">
    <div class="row">
        {% for i in c %}
        <div class="col-sm-4">
            <div class="card" style="width: 30rem;">
  <img src="{{i.image.url}}" class="card-img-top p-1" alt="..." height="250px" width="100%;">
  <div class="card-body">
    <h3 class="card-title text-center">{{i.name}}</h3>
        <a href="{% url 'shop:allproducts' i.name %}" class="btn btn-primary" style="position:relative;left:38%;">PRODUCTS</a>
  </div>
</div>
        </div>{% endfor %}
    </div>
</div>
{% endblock %}

Ecommerce site/ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5" style="margin-bottom:60px;margin-left:200px;">
    <div class="row">
        <div class="col-sm-4"><img src="{{p.image.url}}" height="370px" width="370px"></div>
        <div class="col-sm-5">
            <h4 >{{p.name}}</h4>
            <h5 class="mt-2">{{p.price}}</h5>
            {{p.stock}}
            <p class="mt-2" style="text-indent:20px;line-height:1.8;text-align:justify">{{p.desc}}</p>

            {% if user.is_superuser == False %}


            {% if p.stock <= 0%}
            <h4>Out of Stock</h4>
            {% else %}

            <h4><a href="{% url 'cart:addtocart' p.name %}" class="btn btn-secondary mt-4">Add To Cart</a></h4>
            {% endif %}

            {% else %}
            {% if p.stock <= 0%}
            <h4>Out of Stock</h4>

            <h4><a href="{% url 'admin:index' %}" class="btn btn-secondary mt-4">Add Stock</a></h4>
            {% else %}
             <h4>Product in Stock</h4>
            <h4><a href="{% url 'admin:index' %}" class="btn btn-secondary mt-4">Add Stock</a></h4>


            {% endif %}
                {% endif %}
        </div>
    </div></div>

{% endblock %}

Ecommerce site/ecommerce/templates/login.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
<html lang="en">

{% block content %}
<div class="container-fluid mt-5" style="margin-bottom:60px;">
<h2>LOGIN PAGE</h2>
    <form method="POST">
 {% csrf_token %}
 <div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter the username">
    </div>
    <div  class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="p" placeholder="Enter the password">
    </div>
        <div  class="mb-3">
         <input type="submit" class="form-control">
</div>
    </form>
{% if messages %}
{% for i in messages %}
<ul>
    <li>{{i}}</li>
</ul>
 {% endfor %}
 {% endif %}
</div>
{% endblock %}

Ecommerce site/ecommerce/templates/orderdetail.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
<html lang="en">

{% block content %}
<div class="container-fluid mt-5" style="margin-bottom:60px;">
     <center>
         <h3 class="text-center text-secondary">{{m}}</h3>
         <h5 class="text-center text-success">Thank You...</h5>
         <h6><a href="{% url 'shop:allcat' %}">Continue Shopping</a></h6>
     </center>
</div>
{% endblock %}

Ecommerce site/ecommerce/templates/orderform.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
<html lang="en">

{% block content %}
<div class="container-fluid mt-5" style="margin-bottom:60px;">
<h2>Enter Order Details</h2>
    <form method="POST">
 {% csrf_token %}
 <div class="mb-3">
  <label class="form-label">Address</label>
  <input type="text" class="form-control" name="a" placeholder="Enter the Address">
    </div>
        <div class="mb-3">
  <label class="form-label">Phone</label>
  <input type="text" class="form-control" name="p" placeholder="Enter the Phone">
    </div>
        <div class="mb-3">
  <label class="form-label">Account Number</label>
  <input type="text" class="form-control" name="n" placeholder="Enter the Account Number">
    </div>

        <div  class="mb-3">
         <input type="submit" class="form-control">
</div>
    </form>
{% if messages %}
{% for i in messages %}
<ul>
    <li>{{i}}</li>
</ul>
 {% endfor %}
 {% endif %}
</div>
{% endblock %}

Ecommerce site/ecommerce/templates/orderview.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">

{% block content %}
<div class="container-fluid mt-5" style="margin-bottom:60px;">
    <h4>Customer Name:{{u}}</h4>

    <div class="row">
        <h4>Order Details</h4>
        {% for i in o %}
        <div class="col-sm-3 my-3 py-2 border border-1 border-secondary">
           <center> <img src="{{i.product.image.url}}" height="150px" width="150px"></center>
        </div>
        <div class="col-sm-7 my-3 pe-3  border border-1 border-secondary">
            <b> Delivery Address:{{i.address}}</b><br>
            <b> Customer Phone:{{i.phone}}</b><br>
            <b> Product name:{{i.product.name}}</b><br>
            <b> Price Address:{{i.product.price}}</b><br>
            <b> No of items:{{i.no_of_items}}</b><br>
            <b> Ordered On:{{i.date_ordered}}</b><br>
            <b> DeliveryStatus:<span class="text-danger">{{i.delivery_status}}</span></b><br>
        </div>


    {% endfor %}
        </div>
</div>
{% endblock %}

Ecommerce site/ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-1" style="margin-bottom:60px;">
    <img src="{{c.image.url}}" width="100%" height="450px"></div>
</div>

<div class="container-fluid mt-1" style="margin-bottom:50px;">
     <h3 class="text-center fw-bold pb-3">{{c.name}}</h3>
    <p style="line-height:2;text-align:justify;">{{c.desc}}</p>

</div>
<div class="container=fluid mt-1 rounded rounded-5" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card" style="width: 30rem;">
  <img src="{{i.image.url}}" class="card-img-top p-2" alt="..." height="250px" width="100%;">
  <div class="card-body">
    <h3 class="card-title text-center">{{i.name}}</h3>
      <h5  class="text-center">{{i.price}}</h5>
        <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary" style="position:relative;left:38%;">DETAILS</a>
  </div>
</div>
        </div>{% endfor %}
    </div>
</div>
{% endblock %}

Ecommerce site/ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-5" style="margin-bottom:60px;">

 <h2>REGISTER HERE</h2>
    <form method="POST">
 {% csrf_token %}
 <div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control"  name="u" placeholder="enter the username">
</div>
     <div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p"  placeholder="enter the password">
</div>
     <div class="mb-3">
  <label  class="form-label">Confirm Password</label>
  <input type="password" class="form-control" name="cp" placeholder="enter the confirm password">
</div>
<div class="mb-3">
  <label  class="form-label">email</label>
  <input type="email" class="form-control" name="e" placeholder="enter the email">
</div>

    <div class="mb-3">

    <input type="submit" class="form-control">
    </div>

{% endblock %}

Ecommerce site/ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div ><h4>You Have Searched for <span class="text-danger fw-bolder">{{query}}</span></h4></div>
</center>

<div class="container mt-2 rounded rounded-5" style="margin-bottom:100px;">
     <h3 class="text-center fw-bold pb-3">{{c.name}}</h3>
    <p style="line-height:2;text-align:justify;">{{c.desc}}</p>

</div>
<div class="container mt-2 rounded rounded-5" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card mb-5" style="width:27rem;">
  <img src="{{i.image.url}}" class="card-img-top p-2" alt="..." height="200px" width="100%;">
  <div class="card-body">
    <h3 class="card-title text-center">{{i.name}}</h3>
      <h5  class="text-center">{{i.price}}</h5>
        <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary" style="position:relative;left:38%;">DETAILS</a>
  </div>
</div>

        </div>
{% empty %}
            <h4 class="text-center text-danger">No Search Results Found</h4>
        {% endfor %}
    </div>
</div>










{% endblock %}